### ISSUE TITLE
combined_deu.mrp

### ISSUE THREAD

**Issue by lovodkin93** [ufal/perin#14]
Hello,
I am having a similar error to that described in #7 with `mrp/2020/cl/companion/combined_deu.mrp`.
Is it acquired in a similar manner? Namely:
```
cat cl/companion/deu.mrp cl/evaluation/deu.mrp > cl/companion/combined_deu.mrp
```
Thank you.
@davda54

**Comment by davda54** [comment]
Hi again :) Yes, that should be it. Does it work properly?

**Comment by lovodkin93** [comment]
it seems like it works properly, yes :)
