### ISSUE TITLE
OSError: Model name 'xlm-roberta-base' was not found in model name list

### ISSUE THREAD

**Issue by lovodkin93** [ufal/perin#15]
Hey,
When Trying to train the model for UCCA, I keep getting this error:
```
OSError: Model name 'xlm-roberta-base' was not found in model name list 
(bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, 
bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased, bert-base-japanese, bert-base-japanese-whole-word-masking, bert-base-japanese-char, bert-base-japanese-char-whole-word-masking, bert-base-finnish-cased-v1, bert-base-finnish-uncased-v1, bert-base-dutch-cased).
 We assumed 'https://cdn.huggingface.co/xlm-roberta-base-pytorch_model.bin' was a path or url to model weight files named one of ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt'] but couldn't find any such file at this path or url.
```

I have checked and it appears in older versions of the Transformers package this used to be a problem, but it should've been resolved by version 2.10.0 which is the version required by this project.
So I am a little at loss as to the origin of this error.
Has anyone had a similar problem or might know its origin?
Thanks!
@davda54

**Comment by davda54** [comment]
Hi, I'm sorry but I was not able to replicate this issue. It works correctly on my machine as well as on [Google Colab](https://colab.research.google.com/drive/1jqYATZgv1GhEto4eUKH7_-P8VmHIKGMs?usp=sharing#scrollTo=p32o37bv9okJ). I would suggest reinstalling the `transformers` package / your Python environment.

**Comment by lovodkin93** [comment]
thanks for your reply!
I have actually managed to solve this problem - it appeared it was caused by lack of memory.
