### ISSUE TITLE
large_ucca vs. base_ucca

### ISSUE THREAD

**Issue by lovodkin93** [ufal/perin#16]
Hello,
Have you seen substantial improvements when using the large_ucca configurations vs. the base_ucca configurations?
I have gone over your paper and haven't found any mention of the comparison between the base and large versions.
Thanks!

**Comment by davda54** [comment]
Hi,

I'm sorry but I don't have the base scores anymore. In my experience, larger LMs are always better but it's more convenient to prototype with smaller LMs first. We've evaluated base/large XLM-R on Czech PTG in [this paper (table 7)](https://arxiv.org/pdf/2105.11314.pdf), where the average F-scores are 92.11 vs. 91.55 %. This is roughly what I would expect for UCCA, too. Not a significant improvement.

**Comment by lovodkin93** [comment]
great, thank you!
