### ISSUE TITLE
'combined'?

### ISSUE THREAD

**Issue by lifengjin** [ufal/perin#7]
I noticed that in the MRP data downloaded by me, the companions are just called udpipe.mrp instead of combined_udpipe.mrp. Is there a difference? Are the combined files somehow generated by some script?

**Comment by davda54** [comment]
Hi, thanks for bringing this to my attention! 

~`combined_udpipe.mrp` is the concatenation of `companion/udpipe.mrp` for the cross-framework portion of data, and of `companion/amr.mrp`, `companion/drg.mrp`, `companion/ptg.mrp` and `companion/ucca.mrp` for the cross-lingual portion. I will update the code to reflect this as soon as I find some free time :)~

**Edit:** I'm really sorry for the confusion: `udpipe.mrp` inside the `companion` folder contains only data for the train and the validation datasets, `combined_udpipe.mrp` is the concatenation of this and of `evaluation/udpipe.mrp`; i.e. `cat companion/udpipe.mrp evaluation/udpipe.mrp > companion/combined_udpipe.mrp`.

**Comment by lifengjin** [comment]
Thanks for the info. It works! I am closing the issue.

**Comment by lovodkin93** [comment]
Hey, in the MRP data I downloaded there wasn't an evaluation folder but rather a validation folder with a udpipe.mrp file. 
Should I treat it the same as the evaluation folder when generating the combined_udpipe.mrp file using the cat command? Namely:
```
cat comanion/udpipe.mrp validation/udpipe.mrp > comapnion/combined_udpipe.mrp
```

Thank you.

**Comment by lovodkin93** [comment]
Hello,
I am having a similar error with `mrp/2020/cl/companion/combined_deu.mrp`.
Is it acquired in a similar manner? Namely:
```
cat cl/companion/deu.mrp cl/evaluation/deu.mrp > cl/companion/combined_deu.mrp
```
Thank you.

**Comment by lizhzh8** [comment]
> **in the MRP data  downloaded**
Hello, I am confused where to downloaded the MRP data.If you know,please tell me,thank you .

**Comment by davda54** [comment]
Hi, please contact the authors of the MRP 2020 shared task to get the data: [https://aclanthology.org/2020.conll-shared.1/](https://aclanthology.org/2020.conll-shared.1/)
