### ISSUE TITLE
filter_nonalnum

### ISSUE THREAD

**Issue by lifengjin** [ufal/perin#8]
https://github.com/ufal/perin/blob/51a46ad68eb3b4e02a8328518b92336db957076e/utility/label_processor.py#L29

Here the class calls a method called `filter_out_nonalnum`, but only `filter_nonalnum` is implemented. I assume they are the same, but want to make sure.

**Comment by davda54** [comment]
Thank you very much for noticing, you're right :) It should be corrected now, so I'm closing this issue.
